adjective1 = input("Enter a Adjective: ")
adjective2 = input("Enter a Adjective: ")
adjective3 = input("Enter a Adjective: ")
adjective4 = input("Enter a Adjective: ")
adjective5 = input("Enter a Adjective: ")
celebrity = input("Enter a Celebrity: ")
noun1 = input("Enter a Noun: ")
noun2= input("Enter a Noun: ")
noun3 = input("Enter a Noun: ")
noun4 = input("Enter a Noun: ")
typeOfFood1 = input("Enter a Type of Food: ")
typeOfFood2 = input("Enter a Type of Food: ")
typeOfFood3 = input("Enter a Type of Food: ")

print("I recently had dinner at a new Chinese restraunt. The cooking was " + adjective1 + " and the service was " + adjective2)
print(" The owner of the restraunt, " + celebrity + ", suggested that for my first course I have sweet and " + adjective3 + " spare ribs, which is a specialty of the " + noun1 +".")
print(" They were " + adjective4 + ". For the next course, I was served an " + adjective5 + " " + noun2 + " soup.")
print(" The main course consisted of Egg Foo " + noun3 + ", lobster in " + typeOfFood1 + " sauce, and pressed " + typeOfFood2 + ".")
print(" For dessert, I ordered those famous Chinese " + noun4 + " cookies with sliced " + typeOfFood3 + ".")
print(" But whenever I eat Chinese food, an hour later I feel " + adjective5 + " again.")
